server:
  port: 8080
  contextPath: /

spring:
  datasource:
    tomcat:
      max-wait: 5000
      max-active: 10
      test-on-borrow: true
    username: root
    password: toor
    url: jdbc:h2:file:./database
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    mode: HTML
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  http:
    multipart:
      max-request-size: 5MB
      max-file-size: 12MB

liquibase:
  change-log: classpath:/db/migration/changelog.xml
  enabled: true

asknet:
  timezone: Europe/Moscow
